name: commodity-chain

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: commodity_chain
      POSTGRES_PASSWORD: commodity_chain
      POSTGRES_USER: commodity_chain
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U commodity_chain -d commodity_chain']
      interval: 5s
      timeout: 5s
      retries: 10

  nats:
    image: nats:2.11-alpine
    command: ['-js', '-sd', '/data', '-m', '8222']
    ports:
      - '4222:4222'
      - '8222:8222'
    volumes:
      - nats-data:/data

  redis:
    image: redis:7.4-alpine
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    command: ['start-dev']
    environment:
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
    ports:
      - '8080:8080'
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  keycloak-data:
  nats-data:
  postgres-data:
  redis-data:
